# docker compose -f deployment/docker-compose.yaml up -d                                                                      
version: '0.1'

services:
  mlflow:
    image: 'mlflow_server:latest'
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./savedmodel:/mlflow/savedmodel"
      - "../db/mlruns.db:/mlflow/db/mlruns.db"
      - "../db/registered_model.db:/mlflow/db/registered_model.db"
    environment:
      BACKEND_URI: sqlite:////mlflow/db/mlruns.db
      ARTIFACT_ROOT: ${PWD}/savedmodel
      REGISTERED_STORE_URI: sqlite:///mlflow/db/registered_model.db

    # gives only training container access to its port and container
    # network_mode: "service:training"
    networks:
      - mlnet

  training:
    image: 'mlflowtraining:latest'
    # links:
    #   - "mlflow:https://127.0.0.1:5000"
    volumes:
      - "./savedmodel:/mlflow/savedmodel"
      - "../db/mlruns.db:/mlflow/db/mlruns.db"
      - "../db/registered_model.db:/mlflow/db/registered_model.db"
    environment:
      BACKEND_URI: sqlite:////mlflow/db/mlruns.db
      ARTIFACT_ROOT: ${PWD}/savedmodel
      REGISTERED_STORE_URI: sqlite:///mlflow/db/registered_model.db
    networks:
      - mlnet

networks:
  mlnet:
    name: "mlnet"
    driver: bridge
    ipam:
      config:
          - subnet: "50.1.1.0/24"
            gateway: "50.1.1.4"